-- MySQL Script generated by MySQL Workbench
-- Thu Oct 11 10:03:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`shop0926_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shop0926_auth` (
  `auth_id` MEDIUMINT UNSIGNED NOT NULL COMMENT '权限id',
  `auth_name` VARCHAR(45) NOT NULL DEFAULT '',
  `module_name` VARCHAR(45) NOT NULL DEFAULT 'null' COMMENT '模块名',
  `controller_name` VARCHAR(45) NOT NULL DEFAULT 'null' COMMENT '控制器名',
  `action_name` VARCHAR(45) NOT NULL DEFAULT 'null' COMMENT '方法名称',
  `add_time` MEDIUMINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '添加时间',
  `parent_id` MEDIUMINT UNSIGNED NOT NULL COMMENT '父级id',
  PRIMARY KEY (`auth_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shop0926_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shop0926_role` (
  `role_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '角色名',
  `add_time` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_name_UNIQUE` (`role_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shop0926_role_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shop0926_role_auth` (
  `role_id` MEDIUMINT UNSIGNED NOT NULL COMMENT '角色id',
  `auth_id` MEDIUMINT UNSIGNED NOT NULL COMMENT '权限id',
  INDEX `role_id_idx_auth` (`role_id` ASC),
  INDEX `auth_id_idx_auth` (`auth_id` ASC),
  CONSTRAINT `role_id_auth`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`shop0926_role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `auth_id_auth`
    FOREIGN KEY (`auth_id`)
    REFERENCES `mydb`.`shop0926_auth` (`auth_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shop0926_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shop0926_admin` (
  `admin_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admin_name` VARCHAR(45) NOT NULL DEFAULT '',
  `admin_pwd` CHAR(32) NOT NULL DEFAULT '',
  `is_use` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '是否启用 1启用 0禁用 默认是1',
  `add_time` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `admin_name_UNIQUE` (`admin_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shop0926_admin_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shop0926_admin_role` (
  `admin_id` MEDIUMINT UNSIGNED NOT NULL,
  `role_id` MEDIUMINT UNSIGNED NOT NULL,
  `add_time` INT UNSIGNED NOT NULL DEFAULT 0,
  INDEX `admin_id_idx_admin` (`admin_id` ASC),
  INDEX `role_id_idx_admin` (`role_id` ASC),
  CONSTRAINT `admin_id_role`
    FOREIGN KEY (`admin_id`)
    REFERENCES `mydb`.`shop0926_admin` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_id_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`shop0926_role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
